"""add indexes on frequently filtered columns

Revision ID: 237c2943e4c8
Revises: 4684563934c8
Create Date: 2026-09-23 23:09:50.158100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '237c2943e4c8'
down_revision: Union[str, None] = '4684563934c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_at'), 'bookings', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_type'), 'bookings', ['type'], unique=False)
    op.create_index(op.f('ix_bookings_worker_id'), 'bookings', ['worker_id'], unique=False)
    op.create_index(op.f('ix_certificates_created_at'), 'certificates', ['created_at'], unique=False)
    op.create_index(op.f('ix_certificates_status'), 'certificates', ['status'], unique=False)
    op.create_index(op.f('ix_certificates_worker_id'), 'certificates', ['worker_id'], unique=False)
    op.create_index(op.f('ix_complaints_booking_id'), 'complaints', ['booking_id'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_raised_by'), 'complaints', ['raised_by'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_worker_id'), 'complaints', ['worker_id'], unique=False)
    op.create_index(op.f('ix_cooperatives_created_at'), 'cooperatives', ['created_at'], unique=False)
    op.create_index(op.f('ix_cooperatives_region'), 'cooperatives', ['region'], unique=False)
    op.create_index(op.f('ix_cooperatives_verified'), 'cooperatives', ['verified'], unique=False)
    op.create_index(op.f('ix_earnings_booking_id'), 'earnings', ['booking_id'], unique=False)
    op.create_index(op.f('ix_earnings_created_at'), 'earnings', ['created_at'], unique=False)
    op.create_index(op.f('ix_earnings_date'), 'earnings', ['date'], unique=False)
    op.create_index(op.f('ix_earnings_payment_status'), 'earnings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_earnings_worker_id'), 'earnings', ['worker_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_worker_id'), 'reviews', ['worker_id'], unique=False)
    op.create_index(op.f('ix_service_categories_created_at'), 'service_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_welfare_programs_created_at'), 'welfare_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_welfare_programs_status'), 'welfare_programs', ['status'], unique=False)
    op.create_index(op.f('ix_welfare_programs_type'), 'welfare_programs', ['type'], unique=False)
    op.create_index(op.f('ix_workers_availability'), 'workers', ['availability'], unique=False)
    op.create_index(op.f('ix_workers_cooperative_id'), 'workers', ['cooperative_id'], unique=False)
    op.create_index(op.f('ix_workers_created_at'), 'workers', ['created_at'], unique=False)
    op.create_index(op.f('ix_workers_rating'), 'workers', ['rating'], unique=False)
    op.create_index(op.f('ix_workers_verification_status'), 'workers', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_verification_status'), table_name='workers')
    op.drop_index(op.f('ix_workers_rating'), table_name='workers')
    op.drop_index(op.f('ix_workers_created_at'), table_name='workers')
    op.drop_index(op.f('ix_workers_cooperative_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_availability'), table_name='workers')
    op.drop_index(op.f('ix_welfare_programs_type'), table_name='welfare_programs')
    op.drop_index(op.f('ix_welfare_programs_status'), table_name='welfare_programs')
    op.drop_index(op.f('ix_welfare_programs_created_at'), table_name='welfare_programs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_service_categories_created_at'), table_name='service_categories')
    op.drop_index(op.f('ix_reviews_worker_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_earnings_worker_id'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_payment_status'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_date'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_created_at'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_booking_id'), table_name='earnings')
    op.drop_index(op.f('ix_cooperatives_verified'), table_name='cooperatives')
    op.drop_index(op.f('ix_cooperatives_region'), table_name='cooperatives')
    op.drop_index(op.f('ix_cooperatives_created_at'), table_name='cooperatives')
    op.drop_index(op.f('ix_complaints_worker_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_raised_by'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_booking_id'), table_name='complaints')
    op.drop_index(op.f('ix_certificates_worker_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_status'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_created_at'), table_name='certificates')
    op.drop_index(op.f('ix_bookings_worker_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_type'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    # ### end Alembic commands ###
